services:
  nginx_att_3: # 1er servicio: nginx
    image: nginx:stable-alpine # imagen de docker hub que vamos a usar
    container_name: nginx_att_3 # nombre para referirse al servicio
    ports:
      - "8001:80" # puerto de mi pc:puerto del servicio
    volumes:
      - ./Attendize:/var/www/html # carpeta local/ vincula a carpeta de nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # archivo local / reflejado en archivo de la imagen
      - ./nginx/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on: # para correr este servicio debe estar corriendo php y mysql antes
      - php_att_3
      - mysql_att_3
    networks: # la red que los conecta se llama laravel
      - laravel

  mysql_att_3: # 2do servici
    image: mysql:5.7 # imagen de docker hub
    container_name: mysql_att_3 # nombre de referencia del servicio
    tty: true # aqui si le fallo joven xD, 👀 leo los comentarios
    ports:
      - "33070:3306" # puerto local:puerto del servicio
    volumes:
      - ./mysql:/var/lib/mysql # carpeta local:carpeta de config de mysql
    environment: # datos de configuracion del entorno
      MYSQL_DATABASE: 'blugrin_db' # importante que tengan comillas
      MYSQL_USER: 'blugrin_db'
      MYSQL_PASSWORD: 'Gr1ns0ft22'
      MYSQL_ROOT_PASSWORD: 'rootGr1ns0ft22'
      SERVICE_NAME: mysql_att_3
    networks:
      - laravel # red

  php_att_3: # 3er servicio
    build: # este se construira aqui mismo
      context: . # ruta de referencia ./
      dockerfile: Dockerfile # nombre del archivo de configuracion de la imagen
    container_name: php_att_3
    environment:
      UPLOAD_LIMIT: 512M
    ports:
      - "9001:80"
    volumes: # carpeta de proyecto local : carpeta del container que da vida a los archivos PHP
      - ./Attendize:/var/www/html/
      - ./nginx/zz-docker.conf://usr/local/etc/php-fpm.d/zz-docker.conf
      - ./nginx/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - laravel # red

  phpmyadmin_3:
    container_name: phpmyadmin_3
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql_att_3
    ports:
      - 8013:80
    environment:
      MYSQL_USER: blugrin_db
      MYSQL_PASSWORD: Gr1ns0ft22
      MYSQL_ROOT_PASSWORD: rootGr1ns0ft22
      UPLOAD_LIMIT: 640M
      PMA_HOST: mysql_att_3
    restart: always
    networks:
      - laravel # red

networks: # declaracion de la red
  laravel: